CREATE TYPE "public"."BackgroundRuntimeConfigSection" AS ENUM (
    'OPERATIONAL',
    'ADVANCED',
    'ABUSE_PROTECTION',
    'WORKER_THROUGHPUT'
);

CREATE TYPE "public"."BackgroundRuntimeLeaseName" AS ENUM (
    'BILLING_RECONCILIATION',
    'RECOVERY_CAPACITY_REPAIR',
    'TRANSLATION_RECONCILIATION',
    'QUEUE_CONCURRENCY_RECONCILIATION'
);

CREATE TABLE "public"."BackgroundRuntimeConfig" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "version" INTEGER NOT NULL DEFAULT 0,
    "billingReconciliationIntervalSeconds" INTEGER NOT NULL DEFAULT 60,
    "billingReconciliationShopBatchSize" INTEGER NOT NULL DEFAULT 50,
    "shopifyUsagePublishBatchSize" INTEGER NOT NULL DEFAULT 50,
    "recoveryRepairIntervalSeconds" INTEGER NOT NULL DEFAULT 300,
    "recoveryRepairShopBatchSize" INTEGER NOT NULL DEFAULT 100,
    "recoveryResumeBatchSize" INTEGER NOT NULL DEFAULT 25,
    "translationReconciliationIntervalSeconds" INTEGER NOT NULL DEFAULT 300,
    "translationBatchMaxRequests" INTEGER NOT NULL DEFAULT 100,
    "conversationQuietWindowMs" INTEGER NOT NULL DEFAULT 3000,
    "conversationMaxSettleWindowMs" INTEGER NOT NULL DEFAULT 10000,
    "billingFrozenRecheckSeconds" INTEGER NOT NULL DEFAULT 3600,
    "billingProviderRetrySeconds" INTEGER NOT NULL DEFAULT 300,
    "shopifyUsageRetryBaseSeconds" INTEGER NOT NULL DEFAULT 60,
    "shopifyUsageRetryMaxSeconds" INTEGER NOT NULL DEFAULT 3600,
    "translationReconciliationPageSize" INTEGER NOT NULL DEFAULT 100,
    "translationClaimTimeoutSeconds" INTEGER NOT NULL DEFAULT 900,
    "translationSubmitRetrySeconds" INTEGER NOT NULL DEFAULT 300,
    "translationInitialPollSeconds" INTEGER NOT NULL DEFAULT 300,
    "translationPollIntervalSeconds" INTEGER NOT NULL DEFAULT 300,
    "translationResultRetrySeconds" INTEGER NOT NULL DEFAULT 300,
    "translationSubmitMaxAttempts" INTEGER NOT NULL DEFAULT 3,
    "translationMaxAutoRetries" INTEGER NOT NULL DEFAULT 3,
    "rawSenderLimitPerMinute" INTEGER NOT NULL DEFAULT 60,
    "rawGlobalLimitPerMinute" INTEGER NOT NULL DEFAULT 20000,
    "turnSenderLimitPerMinute" INTEGER NOT NULL DEFAULT 12,
    "turnSenderLimitPerTenMinutes" INTEGER NOT NULL DEFAULT 60,
    "turnConversationLimitPerMinute" INTEGER NOT NULL DEFAULT 12,
    "turnConversationLimitPerTenMinutes" INTEGER NOT NULL DEFAULT 60,
    "turnShopLimitPerMinute" INTEGER NOT NULL DEFAULT 600,
    "turnGlobalLimitPerMinute" INTEGER NOT NULL DEFAULT 5000,
    "discoverySenderLimitPerMinute" INTEGER NOT NULL DEFAULT 4,
    "discoverySenderLimitPerTenMinutes" INTEGER NOT NULL DEFAULT 12,
    "discoveryConversationLimitPerMinute" INTEGER NOT NULL DEFAULT 4,
    "discoveryConversationLimitPerTenMinutes" INTEGER NOT NULL DEFAULT 12,
    "checkoutQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 10,
    "orderQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 5,
    "pendingRecoveryQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 10,
    "recoveryResumeQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 10,
    "whatsappQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 20,
    "merchantCommunicationsQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 10,
    "billingSubscriptionQueueGlobalConcurrency" INTEGER NOT NULL DEFAULT 10,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BackgroundRuntimeConfig_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "ck_arch014_background_runtime_config_version" CHECK ("version" >= 0),
    CONSTRAINT "ck_arch014_background_runtime_config_billing_reconciliation_interval" CHECK ("billingReconciliationIntervalSeconds" BETWEEN 10 AND 3600),
    CONSTRAINT "ck_arch014_background_runtime_config_billing_reconciliation_batch" CHECK ("billingReconciliationShopBatchSize" BETWEEN 1 AND 200),
    CONSTRAINT "ck_arch014_background_runtime_config_shopify_usage_publish_batch" CHECK ("shopifyUsagePublishBatchSize" BETWEEN 1 AND 200),
    CONSTRAINT "ck_arch014_background_runtime_config_recovery_repair_interval" CHECK ("recoveryRepairIntervalSeconds" BETWEEN 30 AND 3600),
    CONSTRAINT "ck_arch014_background_runtime_config_recovery_repair_batch" CHECK ("recoveryRepairShopBatchSize" BETWEEN 1 AND 500),
    CONSTRAINT "ck_arch014_background_runtime_config_recovery_resume_batch" CHECK ("recoveryResumeBatchSize" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_reconciliation_interval" CHECK ("translationReconciliationIntervalSeconds" BETWEEN 30 AND 3600),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_batch_requests" CHECK ("translationBatchMaxRequests" BETWEEN 1 AND 500),
    CONSTRAINT "ck_arch014_background_runtime_config_conversation_quiet_window" CHECK ("conversationQuietWindowMs" BETWEEN 250 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_conversation_settle_window" CHECK ("conversationMaxSettleWindowMs" BETWEEN 1000 AND 30000),
    CONSTRAINT "ck_arch014_background_runtime_config_billing_frozen_recheck" CHECK ("billingFrozenRecheckSeconds" BETWEEN 300 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_billing_provider_retry" CHECK ("billingProviderRetrySeconds" BETWEEN 30 AND 3600),
    CONSTRAINT "ck_arch014_background_runtime_config_shopify_usage_retry_base" CHECK ("shopifyUsageRetryBaseSeconds" BETWEEN 10 AND 3600),
    CONSTRAINT "ck_arch014_background_runtime_config_shopify_usage_retry_max" CHECK ("shopifyUsageRetryMaxSeconds" BETWEEN 60 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_page_size" CHECK ("translationReconciliationPageSize" BETWEEN 1 AND 500),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_claim_timeout" CHECK ("translationClaimTimeoutSeconds" BETWEEN 60 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_submit_retry" CHECK ("translationSubmitRetrySeconds" BETWEEN 30 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_initial_poll" CHECK ("translationInitialPollSeconds" BETWEEN 30 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_poll_interval" CHECK ("translationPollIntervalSeconds" BETWEEN 30 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_result_retry" CHECK ("translationResultRetrySeconds" BETWEEN 30 AND 86400),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_submit_attempts" CHECK ("translationSubmitMaxAttempts" BETWEEN 1 AND 10),
    CONSTRAINT "ck_arch014_background_runtime_config_translation_auto_retries" CHECK ("translationMaxAutoRetries" BETWEEN 0 AND 10),
    CONSTRAINT "ck_arch014_background_runtime_config_raw_sender_limit" CHECK ("rawSenderLimitPerMinute" BETWEEN 1 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_raw_global_limit" CHECK ("rawGlobalLimitPerMinute" BETWEEN 1 AND 1000000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_sender_minute_limit" CHECK ("turnSenderLimitPerMinute" BETWEEN 1 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_sender_ten_minute_limit" CHECK ("turnSenderLimitPerTenMinutes" BETWEEN 1 AND 100000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_conversation_minute_limit" CHECK ("turnConversationLimitPerMinute" BETWEEN 1 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_conversation_ten_minute_limit" CHECK ("turnConversationLimitPerTenMinutes" BETWEEN 1 AND 100000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_shop_limit" CHECK ("turnShopLimitPerMinute" BETWEEN 1 AND 100000),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_global_limit" CHECK ("turnGlobalLimitPerMinute" BETWEEN 1 AND 1000000),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_sender_minute_limit" CHECK ("discoverySenderLimitPerMinute" BETWEEN 1 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_sender_ten_minute_limit" CHECK ("discoverySenderLimitPerTenMinutes" BETWEEN 1 AND 100000),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_conversation_minute_limit" CHECK ("discoveryConversationLimitPerMinute" BETWEEN 1 AND 10000),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_conversation_ten_minute_limit" CHECK ("discoveryConversationLimitPerTenMinutes" BETWEEN 1 AND 100000),
    CONSTRAINT "ck_arch014_background_runtime_config_checkout_queue_concurrency" CHECK ("checkoutQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_order_queue_concurrency" CHECK ("orderQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_pending_recovery_queue_concurrency" CHECK ("pendingRecoveryQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_recovery_resume_queue_concurrency" CHECK ("recoveryResumeQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_whatsapp_queue_concurrency" CHECK ("whatsappQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_merchant_communications_queue_concurrency" CHECK ("merchantCommunicationsQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_billing_subscription_queue_concurrency" CHECK ("billingSubscriptionQueueGlobalConcurrency" BETWEEN 1 AND 100),
    CONSTRAINT "ck_arch014_background_runtime_config_settle_window_order" CHECK ("conversationMaxSettleWindowMs" >= "conversationQuietWindowMs"),
    CONSTRAINT "ck_arch014_background_runtime_config_shopify_retry_order" CHECK ("shopifyUsageRetryMaxSeconds" >= "shopifyUsageRetryBaseSeconds"),
    CONSTRAINT "ck_arch014_background_runtime_config_raw_global_order" CHECK ("rawGlobalLimitPerMinute" >= "rawSenderLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_sender_window_order" CHECK ("turnSenderLimitPerTenMinutes" >= "turnSenderLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_conversation_window_order" CHECK ("turnConversationLimitPerTenMinutes" >= "turnConversationLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_global_order" CHECK ("turnGlobalLimitPerMinute" >= "turnShopLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_turn_shop_order" CHECK ("turnShopLimitPerMinute" >= "turnSenderLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_sender_window_order" CHECK ("discoverySenderLimitPerTenMinutes" >= "discoverySenderLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_conversation_window_order" CHECK ("discoveryConversationLimitPerTenMinutes" >= "discoveryConversationLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_sender_minute_cap" CHECK ("discoverySenderLimitPerMinute" <= "turnSenderLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_sender_ten_minute_cap" CHECK ("discoverySenderLimitPerTenMinutes" <= "turnSenderLimitPerTenMinutes"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_conversation_minute_cap" CHECK ("discoveryConversationLimitPerMinute" <= "turnConversationLimitPerMinute"),
    CONSTRAINT "ck_arch014_background_runtime_config_discovery_conversation_ten_minute_cap" CHECK ("discoveryConversationLimitPerTenMinutes" <= "turnConversationLimitPerTenMinutes")
);

CREATE TABLE "public"."BackgroundRuntimeConfigAuditEvent" (
    "id" TEXT NOT NULL,
    "configId" TEXT NOT NULL,
    "section" "public"."BackgroundRuntimeConfigSection" NOT NULL,
    "expectedVersion" INTEGER NOT NULL,
    "resultingVersion" INTEGER NOT NULL,
    "platformAdminId" TEXT NOT NULL,
    "reason" VARCHAR(1000) NOT NULL,
    "beforeValue" JSONB NOT NULL,
    "afterValue" JSONB NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "BackgroundRuntimeConfigAuditEvent_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "BackgroundRuntimeConfigAuditEvent_configId_fkey" FOREIGN KEY ("configId") REFERENCES "public"."BackgroundRuntimeConfig"("id") ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE INDEX "BackgroundRuntimeConfigAuditEvent_configId_createdAt_idx" ON "public"."BackgroundRuntimeConfigAuditEvent"("configId", "createdAt");
CREATE INDEX "BackgroundRuntimeConfigAuditEvent_platformAdminId_createdAt_idx" ON "public"."BackgroundRuntimeConfigAuditEvent"("platformAdminId", "createdAt");

CREATE TABLE "public"."BackgroundRuntimeLease" (
    "name" "public"."BackgroundRuntimeLeaseName" NOT NULL,
    "ownerToken" TEXT NOT NULL,
    "generation" INTEGER NOT NULL DEFAULT 0,
    "acquiredAt" TIMESTAMP(3) NOT NULL,
    "heartbeatAt" TIMESTAMP(3) NOT NULL,
    "leaseUntil" TIMESTAMP(3) NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "BackgroundRuntimeLease_pkey" PRIMARY KEY ("name")
);

CREATE INDEX "BackgroundRuntimeLease_leaseUntil_idx" ON "public"."BackgroundRuntimeLease"("leaseUntil");

INSERT INTO "public"."BackgroundRuntimeConfig" (
    "id", "version", "billingReconciliationIntervalSeconds", "billingReconciliationShopBatchSize",
    "shopifyUsagePublishBatchSize", "recoveryRepairIntervalSeconds", "recoveryRepairShopBatchSize",
    "recoveryResumeBatchSize", "translationReconciliationIntervalSeconds", "translationBatchMaxRequests",
    "conversationQuietWindowMs", "conversationMaxSettleWindowMs", "billingFrozenRecheckSeconds",
    "billingProviderRetrySeconds", "shopifyUsageRetryBaseSeconds", "shopifyUsageRetryMaxSeconds",
    "translationReconciliationPageSize", "translationClaimTimeoutSeconds", "translationSubmitRetrySeconds",
    "translationInitialPollSeconds", "translationPollIntervalSeconds", "translationResultRetrySeconds",
    "translationSubmitMaxAttempts", "translationMaxAutoRetries", "rawSenderLimitPerMinute", "rawGlobalLimitPerMinute",
    "turnSenderLimitPerMinute", "turnSenderLimitPerTenMinutes", "turnConversationLimitPerMinute",
    "turnConversationLimitPerTenMinutes", "turnShopLimitPerMinute", "turnGlobalLimitPerMinute",
    "discoverySenderLimitPerMinute", "discoverySenderLimitPerTenMinutes", "discoveryConversationLimitPerMinute",
    "discoveryConversationLimitPerTenMinutes", "checkoutQueueGlobalConcurrency", "orderQueueGlobalConcurrency",
    "pendingRecoveryQueueGlobalConcurrency", "recoveryResumeQueueGlobalConcurrency", "whatsappQueueGlobalConcurrency",
    "merchantCommunicationsQueueGlobalConcurrency", "billingSubscriptionQueueGlobalConcurrency", "updatedAt"
) VALUES (
    'default', 0, 60, 50, 50, 300, 100, 25, 300, 100, 3000, 10000, 3600, 300, 60, 3600,
    100, 900, 300, 300, 300, 300, 3, 3, 60, 20000, 12, 60, 12, 60, 600, 5000, 4, 12, 4, 12,
    10, 5, 10, 10, 20, 10, 10, CURRENT_TIMESTAMP
) ON CONFLICT ("id") DO NOTHING;